azs:
- name: z1
- name: z2
- name: z3
compilation:
  az: z1
  network: private
  reuse_compilation_vms: true
  vm_type: default
  workers: 5
disk_types:
- name: 1GB
  disk_size: 1024
- disk_size: 1024
  name: default
networks:
- name: private
  subnets:
  - azs:
    - z1
    - z2
    - z3
    dns:
    - 8.8.8.8
    gateway: 10.244.0.1
    range: 10.244.0.0/24
    reserved:
    - 10.244.0.86
    static:
    - 10.244.0.34
  type: manual
vm_types:
- name: default
