---
name: consul

stemcells:
- alias: linux
  os: ubuntu-xenial
  version: latest

releases:
- name: consul
  version: create
  url: file:///Users/d058546/go/src/github.com/cloudfoundry-incubator/consul-release

update:
  canaries: 1
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000

instance_groups:
- name: consul
  instances: 3
  azs:
  - z1
  - z2
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: { from: common_link }
      consul_server: { from: server_link }
      consul_client: { from: client_link }
    provides:
      consul_common: { as: common_link, shared: true }
      consul_server: { as: server_link, shared: true }
      consul_client: { as: client_link, shared: true }
    properties:
      consul:
        agent:
          mode: server
          log_level: info
          domain: cf.internal
        encrypt_keys:
        - ((consul_encrypt_key))
        agent_cert: ((consul_agent.certificate))
        agent_key: ((consul_agent.private_key))
        ca_cert: ((consul_agent.ca))
        server_cert: ((consul_server.certificate))
        server_key: ((consul_server.private_key))
  stemcell: linux
  vm_type: default
  persistent_disk_type: 1GB
  networks:
  - name: private

variables:
- name: consul_encrypt_key
  type: password
- name: consul_agent_ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
