---
releases:
- name: consul
  version: create
  url: file:///Users/d058546/go/src/github.com/cloudfoundry-incubator/consul-release

addons:
- name: consul_agent
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul_common: { from: common_link, deployment: consul }
    properties:
      consul:
        server:
          tls: ((/consul_server_tls))
        agent:
          tls: ((/consul_agent_tls))
          log_level: info
          domain: cf.internal
        encrypt_keys:
        - ((/consul_encrypt_key))



variables:
- name: /consul_encrypt_key
  type: password
- name: /consul_agent_ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: /consul_agent_tls
  type: certificate
  options:
    ca: /consul_agent_ca
    common_name: consul_agent
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
- name: /consul_server_tls
  type: certificate
  options:
    ca: /consul_agent_ca
    common_name: server.dc1.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth